### ISSUE TITLE
Change error type to be opaque or non-exhaustive

### ISSUE THREAD

**Issue by LPGhatguy** [Kampfkarren/roblox-install#25]
Currently, the crate's error type is just an enum. That means it's a breaking change to add new kinds of error because consumers could be exhaustively matching on the error type today.

There are two good ways to resolve this:

1. Switch the error type to be opaque, like a struct wrapping an enum. The `snafu` crate is great for this, and a bunch more, and could improve error messages too.
2. Mark the enum with `#[non_exhaustive]`. This would require Rust 1.40, which is very recent, and also precludes further changes to existing error variants like including stack traces or file paths.

**Comment by Kampfkarren** [comment]
Just adding `#[non_exhaustive]` or a `#[doc(hidden)] __NonExhaustive` sounds good enough, I think.

**Comment by Kampfkarren** [comment]
It's been a year, `#[non_exhaustive]` is old enough. I still think we should probably move to something like `thiserror` though alongside it.
