### ISSUE TITLE
Install plugin command

### ISSUE THREAD

**Issue by jeparlefrancais** [Kampfkarren/roblox-install#9]
It would be useful to be able to install plugins from the command line with something like this
```
roblox-install plugin some-plugin.lua
```
It could have some kind of options to allow installation with a symlink for like plugin development.

I have not thought much more about it, but I feel like it could be useful for some stuff. I can imagine having something like a studio profile manager that would install and remove plugins depending of the profile I want.

I am not sure it should be built-in roblox-install or not though, let me know what you think!

**Comment by Kampfkarren** [comment]
I'm not sure this is within scope of roblox-install, no? It's something you could use roblox-install *for* though.
